import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

/**
 * Share cards live in `public/images/og/`, generated by
 * `scripts/build-og-images.mjs` and named after the post slug. Resolving them
 * by convention keeps the frontmatter about the post's own illustration and
 * leaves the crawler-facing variant out of the author's hands.
 */
const PUBLIC_DIR = fileURLToPath(new URL('../../public/', import.meta.url));

export const ogImage = (name: string): string | undefined => {
  const path = `/images/og/${name}.jpg`;
  return existsSync(join(PUBLIC_DIR, path)) ? path : undefined;
};

/** Used by every page that isn't a post, and by posts without an image. */
export const DEFAULT_OG_IMAGE = ogImage('site') ?? '/images/logo.png';
